import 'dart:math';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:taul/infrastructure/security/entry_auth_service.dart';

/// Creates an [EntryAuthService] with minimal Argon2id parameters for fast
/// test execution. Each hash takes <10ms instead of ~2s with defaults.
EntryAuthService createFastAuthService() {
  return EntryAuthService(
    argon2id: Argon2id(
      memory: 1024,
      iterations: 1,
      parallelism: 1,
      hashLength: 32,
    ),
  );
}

/// Creates a fake [EntryAuthService] that overrides cryptographic operations
/// with instant alternatives. Use this in widget tests that trigger
/// [generateBackupCodes] or [hashMasterPassword] via the UI.
///
/// Backup codes are generated by running SHA-256 on the plain code rather
/// than Argon2id, and key derivation is a simple HMAC-like operation.
EntryAuthService createFakeAuthService() {
  return _FakeAuthService();
}

/// Converts bytes to a hex string representation.
String bytesToHex(Uint8List bytes) {
  final buffer = StringBuffer();
  for (final byte in bytes) {
    buffer.write(byte.toRadixString(16).padLeft(2, '0'));
  }
  return buffer.toString();
}

/// Generates a deterministic hash-like string (not cryptographic).
/// Used only in tests where we don't need real security.
String _fakeHash(String password, Uint8List salt) {
  final input = '$password:${bytesToHex(salt)}';
  final code = input.hashCode;
  return code.toRadixString(16).padLeft(64, '0');
}

class _FakeAuthService extends EntryAuthService {
  _FakeAuthService() : super(
    argon2id: Argon2id(memory: 1024, iterations: 1, parallelism: 1, hashLength: 32),
  );

  final _random = Random.secure();

  @override
  Future<String> hashMasterPassword({
    required String password,
    required Uint8List salt,
  }) async {
    return _fakeHash(password, salt);
  }

  @override
  Future<Uint8List> deriveMasterKey({
    required String password,
    required Uint8List salt,
  }) async {
    final hash = _fakeHash(password, salt);
    // Return exactly 32 bytes for AES-256
    final bytes = Uint8List(32);
    final hashBytes = Uint8List.fromList(hash.codeUnits);
    for (var i = 0; i < 32; i++) {
      bytes[i] = hashBytes[i % hashBytes.length];
    }
    return bytes;
  }

  @override
  Future<BackupCodeResult> generateBackupCodes({int count = 10}) async {
    final plainCodes = <String>[];
    final codeHashes = <String>[];

    for (var i = 0; i < count; i++) {
      final code = _generateBackupCode();
      final salt = Uint8List(8);
      for (var j = 0; j < 8; j++) {
        salt[j] = _random.nextInt(256);
      }
      final hash = await hashMasterPassword(password: code, salt: salt);
      codeHashes.add('${bytesToHex(salt)}:$hash');
      plainCodes.add(code);
    }

    return BackupCodeResult(plainCodes: plainCodes, codeHashes: codeHashes);
  }

  String _generateBackupCode() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    final buffer = StringBuffer();
    for (var i = 0; i < 8; i++) {
      if (i == 4) buffer.write('-');
      buffer.write(chars[_random.nextInt(chars.length)]);
    }
    return buffer.toString();
  }
}
